//admin
//YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

//User
//a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr



// TESTING INSTRUCTION's USE CASES

//******************//only admin can add and delete movie types
//******************//user can view all movie types

### PUT new genre as admin
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Content-Type: application/json
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

{
  "name": "test genre",
  "speed": "my test",
  "popularityScore": 3.1
}

### GET created genre as admin
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

### DELETE genre as admin
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

### PUT new genre as user - error
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Content-Type: application/json
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

{
  "name": "test genre",
  "speed": "my test",
  "popularityScore": 3.1
}

### DELETE genre as user - error
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

//******************//user can view all movie types

### GET all genres as user
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

//******************//everyone can add a new user

### PUT new user
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/users/391a9234-d715-4feb-8624-ae9cebd0dbe4
Content-Type: application/json

{
  "login": "janko",
  "username": "V3gaBOND",
  "password": "janeczko",
  "email": "janko@wp.pl"
}
### GET all users
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/users
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

//******************//admin can view all movies

### GET all movies as admin
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu


//******************//user can only view his movies

### GET all movies as user
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

//******************//admin can add and delete all elements

### PUT new movie as admin
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu
Content-Type: application/json

{
  "title": "Super film",
  "director": "Jan Cameron",
  "movieFormat": "BLU_RAY",
  "genre": "cdfbd2ad-7c1e-48d7-9f91-2d6d0c089b60",
  "user": "665e4aba-0640-49c2-b71f-4ddf1f9674ba"
}


### GET created movie as admin
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

### DELETE created movie as user (not the owner)
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

### DELETE created movie as admin
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu


//******************// user can add elements

### PUT new movie as user
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies/cbfef27d-e38b-4651-ad1e-0385d25cd89d
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr
Content-Type: application/json

{
  "title": "Super film 2",
  "director": "Jan Cameron 2",
  "movieFormat": "BLU_RAY",
  "genre": "cdfbd2ad-7c1e-48d7-9f91-2d6d0c089b60"
}

### GET created movie as user
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies/cbfef27d-e38b-4651-ad1e-0385d25cd89d
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

### GET created movie as user (all his movies)
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

### DELETE created movie as user (owner)
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies/cbfef27d-e38b-4651-ad1e-0385d25cd89d
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr