//admin
//YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

//User
//a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr



// TESTING INSTRUCTION's USE CASES

//******************//only admin can add and delete weapon types
//******************//player can view all weapon types

### PUT new genre as admin
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Content-Type: application/json
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

{
  "name": "test genre",
  "speed": "my test",
  "popularityScore": 3.1
}

### GET created genre as admin
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

### DELETE genre as admin
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

### PUT new genre as player - error
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Content-Type: application/json
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

{
  "name": "test genre",
  "speed": "my test",
  "popularityScore": 3.1
}

### DELETE WEAPON TYPE as player - error
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres/6abd5ba8-37ff-4c0c-8e75-b3baa6632e05
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

//******************//player can view all weapon types

### GET all genres as player
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/genres
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

//******************//everyone can add a new player

### PUT new player
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/players/391a9234-d715-4feb-8624-ae9cebd0dbe4
Content-Type: application/json

{
  "login": "vegabond@game.com",
  "username": "V3gaBOND",
  "birthDate": "1990-01-01",
  "heroName": "SneakyThief",
  "password": "Shhhh!!!Quiet"
}

### GET all players
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/players
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

//******************//admin can view all weapons

### GET all weapons as admin
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/weapons
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu


//******************//player can only view his weapons

### GET all weapons as player
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/movies
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

//******************//admin can add and delete all elements

### PUT new weapon as admin
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/weapons/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu
Content-Type: application/json

{
  "name": "Bow of The Shadows",
  "damage": "95",
  "weight": "6",
  "value": "1900",
  "weaponType": "cdfbd2ad-7c1e-48d7-9f91-2d6d0c089b60",
  "player": "665e4aba-0640-49c2-b71f-4ddf1f9674ba"
}

### GET created weapon as admin
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/weapons/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu

### DELETE created weapon as player (not the owner)
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/weapons/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

### DELETE created weapon as admin
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/weapons/73e54c57-0e7d-4f03-bcd2-5385877f2d1b
Authorization: Basic YWRtaW4tc2VydmljZTphZG1pbmFkbWlu


//******************// player can add elements

### PUT new weapon as player
// @no-cookie-jar
PUT http://localhost:9083/labs1-1.0-SNAPSHOT/api/weapons/cbfef27d-e38b-4651-ad1e-0385d25cd89d
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr
Content-Type: application/json

{
  "name": "Sword of madness",
  "damage": "40",
  "weight": "2",
  "value": "300",
  "weaponType": "ef47b366-7352-417f-a232-c530e65d7226"
}

### GET created weapon as player
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/weapons/cbfef27d-e38b-4651-ad1e-0385d25cd89d
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

### GET created weapon as player (all his weapons)
// @no-cookie-jar
GET http://localhost:9083/labs1-1.0-SNAPSHOT/api/weapons
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr

### DELETE created weapon as player (owner)
// @no-cookie-jar
DELETE http://localhost:9083/labs1-1.0-SNAPSHOT/api/weapons/cbfef27d-e38b-4651-ad1e-0385d25cd89d
Authorization: Basic a3J6eXN6dG9mMTIzOmtyenlzenRvZmVr