# Get all genres.

GET http://localhost:9082/movieRental/api/genres

###

# create genre

PUT http://localhost:9082/movieRental/api/genres/9e1a6242-0164-4044-9006-bbb57d14ef19
Content-Type: application/json

{
  "name": "drama",
  "popularityScore": 4.1,
  "description": "testtttt"
}

###

# update genre

PATCH http://localhost:9082/movieRental/api/genres/9e1a6242-0164-4044-9006-bbb57d14ef19
Content-Type: application/json

{
  "popularityScore": 7.2,
  "description": "super test"
}

###

# Get single genre.

GET http://localhost:9082/movieRental/api/genres/9e1a6242-0164-4044-9006-bbb57d14ef19

###

# delete genre.

DELETE http://localhost:9082/movieRental/api/genres/9e1a6242-0164-4044-9006-bbb57d14ef19


### Movies

# Get all movies.

GET http://localhost:9082/movieRental/api/movies

###

PUT http://localhost:9082/movieRental/api/genres/9e1a6242-0164-4044-9006-bbb57d14ef19/movies/580a1cb0-2e6a-4b43-86a3-1033c9bde55b
Content-Type: application/json

{
  "title": "test",
  "director": "robert",
  "movieFormat": "BLU_RAY",
  "user": "856248d3-e719-496f-bb7a-49ec3210a710"
}

###

PATCH http://localhost:9082/movieRental/api/movies/580a1cb0-2e6a-4b43-86a3-1033c9bde55b
Content-Type: application/json

{
  "title": "zmiana nazwy",
  "director": "marek",
  "movieFormat": "DVD"
}

###

# Get all movies of a given genre

GET http://localhost:9082/movieRental/api/genres/9e1a6242-0164-4044-9006-bbb57d14ef19/movies

###

# Get a movie

GET http://localhost:9082/movieRental/api/movies/580a1cb0-2e6a-4b43-86a3-1033c9bde55b

###

# Remove a movie

DELETE http://localhost:9082/movieRental/api/movies/580a1cb0-2e6a-4b43-86a3-1033c9bde55b

### USERS

# get all users

GET http://localhost:9082/movieRental/api/users

###

# create user

PUT http://localhost:9082/movieRental/api/users/0ca05b76-9b5a-4451-98b2-3f31f1d75589
Content-Type: application/json

{
  "username": "test",
  "email": "tescioch@awp.pl"
}

###

# Get user.

GET http://localhost:9082/movieRental/api/users/0ca05b76-9b5a-4451-98b2-3f31f1d75589